version: 2

python:
   version: 3.8
   install:
      - method: pip
        path: .
        extra_requirements:
           - docs/requirements.txt
      - method: setuptools
        path: .

sphinx:
    configuration: docs/conf.py
