# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install VapourSynth
      run: |
        sudo apt-get install python3.8-dev
        pip install cython
        
        git clone https://github.com/sekrit-twc/zimg.git --branch v2.9 --depth 1
        pushd zimg
        ./autogen.sh
        ./configure
        sudo make install
        popd
        
        git clone https://github.com/vapoursynth/vapoursynth.git --branch R50 --depth 1
        pushd vapoursynth
        ./autogen.sh
        ./configure
        sudo make install
        popd
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Running tests
      run: |
        python setup.py test
