# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install VapourSynth
      run: |
        curl https://github.com/sekrit-twc/zimg/archive/v2.9.zip --output zimg-v2.9.zip
        mkdir zimg
        pushd zimg
        unzip ../zimg-v2.9.zip
        ./autogen.sh
        ./configure
        make install
        popd
        
        curl https://github.com/vapoursynth/vapoursynth/archive/R50.zip --output vs-r50.zip
        mkdir vs
        pushd vs
        unzip ../vs-r50.zip
        ./autogen.sh
        ./configure
        make install
        popd
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Running tests
      run: |
        python setup.py test
